### ISSUE TITLE
Error después de la instalación

### ISSUE THREAD

**Issue by nmella** [khipu/magento2-khipu#1]
Hola,

Acabo de seguir las instrucciones y me arrojó el siguiente error al tratar de instalarlo en el sitio web [www.peta.cl](https://www.peta.cl):

`composer require khipu/magento2-khipu`

`"Using version ^2.2 for khipu/magento2-khipu ./composer.json has been updated Loading composer repositories with package information Updating dependencies (including require-dev) Package operations: 2 installs, 0 updates, 0 removals - Installing khipu/khipu-api-client (2.7.1): Downloading (100%) - Installing khipu/magento2-khipu (2.2.0): Downloading (100%) Package sjparkinson/static-review is abandoned, you should avoid using it. Use phpro/grumphp instead. Writing lock file Generating autoload files`

Ahora al abrir el sitio web, obtengo:

`Module 'Khipu_Payment' from '/chroot/home/petacl2/peta.cl/html/app/code/Khipu/Payment' has been already defined in '/chroot/home/petacl2/peta.cl/html/vendor/khipu/magento2-khipu'.`

**Comment by cfficaurzua** [comment]
Hola tengo el mismo error 
utilizando php5.6 y magento 2.1.15

**Comment by Richardmaximun** [comment]
Ese error  json de la instalacion no esta bien configurado y lo que dice efectivamente es que se duplicó la instalación:

'/chroot/home/petacl2/peta.cl/html/**APP/CODE/KHIPU**/Payment' '/chroot/home/petacl2/peta.cl/html/**VENDOR/KHIPU**/magento2-khipu'

Solucion:

1. Respalda la carpeta "app/code/khipu" y luego eliminala
2. Ejecuta lo siguiente:

php bin/magento setup:upgrade
php bin/magento setup:di:compile

Es todo.

**Comment by fedekrum** [comment]
> Ese error json de la instalacion no esta bien configurado y lo que dice efectivamente es que se duplicó la instalación:
> 
> '/chroot/home/petacl2/peta.cl/html/**APP/CODE/KHIPU**/Payment' '/chroot/home/petacl2/peta.cl/html/**VENDOR/KHIPU**/magento2-khipu'
> 
> Solucion:
> 
> 1. Respalda la carpeta "app/code/khipu" y luego eliminala
> 2. Ejecuta lo siguiente:
> 
> php bin/magento setup:upgrade
> php bin/magento setup:di:compile
> 
> Es todo.

El problema es que el paquete instala el modulo en 2 lugares simultaneamente

Lo que no entiendo es porque respaldas y luego eliminas

Si eliminas app/code/khipu, no tendras un "return_url" valido y tus pedidos quedaran eternamente como pendientes.
Tengo este problema con un Magento 2.4 recien instalado y no se como solucionarlo

**Comment by fedekrum** [comment]
Este es el mensaje que me mando una persona de soporte de Khipu.

> Juan Carlos (Soporte)
> 13 ago. 2020 17:50 GMT-4
> 
> Hola Federico,
> Estoy viendo un problema similar con un cliente que opera con Magento 2.4, reportado hoy.
> En concreto, al parecer el plugin no corre en dicha versión.
> Lo informé al área encargada, no obstante no existe una fecha o plazo definido para la mejora.
> Si tienes más consultas, no dudes en preguntar por esta vía.
> 
> Saludos,
> 
> Juan Carlos
> https://khipu.com

Asi que por ahora no va a funcionar en 2.4 correctamente.

**Comment by rodrigopooley** [comment]
@fedekrum en Magento 2.3.5-p1 está funcionando. Ya llevo unos 5 meses operativo sin problemas. Estaba haciendo pruebas y a primera vista es un tema de PHP. Seguramente Khipu tendrá que actualizar a lo menos a PHP 7.4. Especialmente si ya no habrán actualizaciones en versiones anteriores de PHP por parte de Magento.

**Comment by fedekrum** [comment]
> @fedekrum en Magento 2.3.5-p1 está funcionando. Ya llevo unos 5 meses operativo sin problemas. Estaba haciendo pruebas y a primera vista es un tema de PHP. Seguramente Khipu tendrá que actualizar a lo menos a PHP 7.4. Especialmente si ya no habrán actualizaciones en versiones anteriores de PHP por parte de Magento.

Definitivamente no anda en Magento 2.4.
Las compras quedan siempre pendientes., jamas cambian de estado a "procesando"
No hay forma de que magento sepa que el pago ha sido efectuado automaticamente.

**Comment by rodrigopooley** [comment]
> > @fedekrum en Magento 2.3.5-p1 está funcionando. Ya llevo unos 5 meses operativo sin problemas. Estaba haciendo pruebas y a primera vista es un tema de PHP. Seguramente Khipu tendrá que actualizar a lo menos a PHP 7.4. Especialmente si ya no habrán actualizaciones en versiones anteriores de PHP por parte de Magento.
> 
> Definitivamente no anda en Magento 2.4.
> Las compras quedan siempre pendientes., jamas cambian de estado a "procesando"
> No hay forma de que magento sepa que el pago ha sido efectuado automaticamente.

El módulo de Khipu en ese sentido no está del todo bien configurado y puede que lo que comentes no sea por un tema de Magento 2.4. Las compras confirmadas siempre te quedan pendientes, al igual que las rechazadas. Las rechazadas deberían quedar canceladas para poder reponer los inventarios en el sitio y el cliente pueda volver a intentar el pago de los stocks originalmente solicitados. Por el momento es un trabajo manual el que hay que hacer ahí. Es una sugerencia hecha hace rato, ya que en su misma plataforma tampoco puedes consultar las transferencias rechazadas. Una consulta que es posible hacer en otras plataformas del mismo tipo.
Otra cosa importante es que Magento 2 por default no notifica a los clientes de las compras exitosas cuando el pago se ha hecho a través de una plataforma de terceros como Khipu. Te recomiendo una extensión de Magecomp https://magecomp.com/magento-2-order-confirmation-email.html
